<a href="https://colab.research.google.com/github/ronin207/Python-Analytics/blob/main/Lecture04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NUS Python for Analytics Lecture 04

#### Functions, Methods and Packages
<ul>
  <li>Functions (Namespaces, Arguments)</li>
  <li>Modules (Numpy)</li>
  <li>Numpy for Scientific Calculation</li>
</ul>

#### **Required Assignment: Newsvendor Case (continued)**

Questions
<ol>
  <li>Calculate the expected values of the demands of <code>paper1</code>  and <code>paper2</code> .</li>
  <li>Calculate the standard deviation of paper demands expressed as:<br>
$𝜎_𝐷=\sqrt{\Sigma_{s=1}^S p_s(d_s−𝔼(𝐷_{𝑝𝑎𝑝𝑒𝑟}))^2}$ <br>Display the results with three decimal digits.</li>
  <li>Suppose that the costs of <code>paper1</code> and <code>paper2</code> are 0.6 and 0.8, and the selling prices of paper1 and paper2 are 1.00 and 1.15, respectively. Calculate the expected total profit if the newsboy has ordered 430 pieces of <code>paper1</code> and 380 pieces of <code>paper2</code>. Print the results with two decimal digits.
  <li>Write a function <code>sold_fun</code> to calculate the expected sold quantities. The input arguments are:
  <ul type="circle">
    <li>The order quantity as a one-dimensional array order.</li>
    <li>The discrete distribution expressed as a two-dimensional array distr.</li>
  </ul>
  </li>

#### **Case Study: A Newsvendor Problem (Array Version)**

***Background***: In this case study, we will solve the previous newsvendor problem using NumPy arrays, in order to show the benefits of element-wise operations. The discrete probability distribution is again given as the following table.

|           | probabilities | paper1  | paper2   |
|-----------|---------------|---------|--------- |
Sunny       | 0.315         | 560     | 533      
Cloudy      | 0.226         | 530     | 486
Raining     | 0.289         | 389     | 386
Thunderstorm| 0.087         | 202     | 234
Haze        | 0.083         | 278     | 263

The table above is expressed by the two-dimensional NumPy array <code>distr</code>.

In [1]:
import numpy as np

distr = np.array([[0.315, 0.226, 0.289, 0.087, 0.083],
                  [560, 530, 389, 202, 278],
                  [533, 486, 386, 234, 263]])

distr

array([[3.15e-01, 2.26e-01, 2.89e-01, 8.70e-02, 8.30e-02],
       [5.60e+02, 5.30e+02, 3.89e+02, 2.02e+02, 2.78e+02],
       [5.33e+02, 4.86e+02, 3.86e+02, 2.34e+02, 2.63e+02]])

In [2]:
# Calculating the sum of products between 
# the probability and demand of each papers (paper1 and paper2) 
# respective to their categories
expected_demand = (distr[0] * distr[1:]).sum(axis=1)
expected_demand

array([449.249, 431.472])

In [3]:
# Using the method to calculate variance,
# the array is converted into a 2D array and summed
# By sqrt the variance, we obtain the standard_deviation
standard_dev = (distr[0] * (distr[1:] - expected_demand.reshape((2, 1))) ** 2).sum(axis=1) ** 0.5
standard_dev

array([118.90763222, 101.3157797 ])

In [4]:
# First declare the array variable for order to store the new information
# Using np.minimum, we extract the minimum values to obtain an accurate expected_sold value
order = np.array([430, 380])
expected_sold = (distr[0] * np.minimum(order.reshape((2, 1)), distr[1:])).sum(axis=1)
expected_sold

array([385.699, 357.587])

In [5]:
# First declare the array variable for cost and price to store the new informations
# price * expected_sold - cost * order and sum the results the get the expected_profit
cost = np.array([0.6, 0.8])
price = np.array([1.00, 1.15])
expected_profit = (price * expected_sold - cost * order).sum()
print("The Expected Profit is ${0:0.2f}".format(expected_profit))

The Expected Profit is $234.92


In [6]:
# Create a function sold_fun taking in distr and order variables
# Calculate the number of orders from the order array
# and reshape according to the number of orders
# Perform a similar method from above
def sold_fun(distr, order):
  order_number = len(order)
  expected_sold_values = (distr[0] * np.minimum(order.reshape((order_number, 1)), distr[1:])).sum(axis=1)
  return expected_sold_values

sold_fun(distr, order)

array([385.699, 357.587])